#!/bin/bash

# NOTE: do not run this script from another directory
# alternatively, go to the fuseki directory to run directly, e.g.:
#
# cd fuseki
# java -Xmx120M -cp "fuseki-server.jar:../target/classes/" org.apache.jena.fuseki.cmd.FusekiCmd --file ../dataset.rdf /ds


# config.ttl can be copied to "fuseki/run/"
FUSEKI_HOME=fuseki FUSEKI_BASE=fuseki/run  java -Dlog4j.configuration=file:./config/log4j.properties -Xmx1200M -cp "target/classes/:fuseki/fuseki-server.jar" org.apache.jena.fuseki.cmd.FusekiCmd --config config/config.ttl 
#--jetty-config config/jetty.xml --timeout=500,500
#  -Dlog4j.configuration=file:./config/log4j.properties' not working properly


